services:
  - type: web
    name: cine-scraper-api
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 3001